# Generated by Django 4.0.2 on 2022-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True)),
                ('genre', models.CharField(choices=[('ROMANCE', 'ROMANCE'), ('FICTION', 'FICTION'), ('ACTION', 'ACTION'), ('ADVENTURE', 'ADVENTURE'), ('COMEDY', 'COMEDY')], max_length=10)),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
