# Generated by Django 4.0.2 on 2022-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
